joint_names: [joint1, joint2, joint3, joint4, joint5] 
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

#joint1_position_controller:
  #type: effort_controllers/JointPositionController
#  type: position_controllers/JointPositionController
#  joint: "joint1"

#joint2_position_controller:
  #type: effort_controllers/JointPositionController
#  type: position_controllers/JointPositionController
#  joint: "joint2"

#joint3_position_controller:
  #type: effort_controllers/JointPositionController
#  type: position_controllers/JointPositionController
#  joint: "joint3"

#joint4_position_controller:
  #type: effort_controllers/JointPositionController
#  type: position_controllers/JointPositionController
#  joint: "joint4"

joint1_velocity_controller: 
  type: velocity_controllers/JointVelocityController
  joint: "joint1"

joint2_velocity_controller: 
  type: velocity_controllers/JointVelocityController
  joint: "joint2"

joint3_velocity_controller: 
  type: velocity_controllers/JointVelocityController
  joint: "joint3"

joint4_velocity_controller: 
  type: velocity_controllers/JointVelocityController
  joint: "joint4"


