red: 
  wp_manipulator:
    joint1_position_controller:
      #type: effort_controllers/JointPositionController
      type: position_controllers/JointPositionController
      joint: "red/wp_manipulator/joint1"

    joint2_position_controller:
      #type: effort_controllers/JointPositionController
      type: position_controllers/JointPositionController
      joint: "red/wp_manipulator/joint2"

    joint3_position_controller:
      #type: effort_controllers/JointPositionController
      type: position_controllers/JointPositionController
      joint: "red/wp_manipulator/joint3"

    joint4_position_controller:
      #type: effort_controllers/JointPositionController
      type: position_controllers/JointPositionController
      joint: "red/wp_manipulator/joint4"

    joint5_position_controller:
      type: position_controllers/JointPositionController
      joint: "red/wp_manipulator/joint5"

