joint_manip_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

manipulator_position_controller:
  type: position_controllers/JointGroupPositionController
  joints: 
    - red/movable_mass_x_joint_0
    - red/movable_mass_y_joint_0
    - red/movable_mass_z_joint_0

gazebo_ros_control:   
  pid_gains:
    red/movable_mass_x_joint_0:
      p: 50
      i: 0.01 
      d: 5.0

gazebo_ros_control:   
  pid_gains:
    red/movable_mass_y_joint_0:
      p: 50
      i: 0.01 
      d: 5.0

gazebo_ros_control:   
  pid_gains:
    red/movable_mass_z_joint_0:
      p: 100
      i: 0.15
      d: 25.0