<?xml version="1.0"?>

<robot xmlns:xacro="http://ros.org/wiki/xacro">

  <!-- Macro for propeler tilting joint and link.-->

  <xacro:macro name="prop_tilt" 
    params="robot_namespace parent number x_axis y_axis mass length radius *origin">

    <joint name="${robot_namespace}/tilt_joint_${number}" type="revolute">
      <xacro:insert_block name="origin"/>
      <parent link="${parent}"/>
      <child link="${robot_namespace}/tilt_link_${number}"/>
      <axis xyz="${x_axis} ${y_axis} 0"/>
      <limit lower="-0.785398163" upper="0.785398163" effort="100000" velocity="3"/>
    </joint>
    
    <link name="${robot_namespace}/tilt_link_${number}">
      <visual>
        <origin rpy="0 0 0" xyz="0 0 ${length/2}"/>
        <geometry>
          <cylinder length="${length}" radius="${radius}" />
        </geometry>
      </visual>
      
      <inertial>
        <origin rpy="0 0 0" xyz="0 0 ${length/2}"/>
        <mass value="${mass}" />
        <inertia
            ixx="${1/12 * mass * (3.0 * radius * radius + length * length)}"      ixy="0.0"                                                             ixz="0.0"
            iyx="0.0"                                                             iyy="${1/12 * mass * (3.0 * radius * radius + length * length)}"      iyz="0.0"
            izx="0.0"                                                             izy="0.0"                                                             izz="${1/2 * mass * radius * radius}" />
      </inertial>
    </link>
  </xacro:macro>

  <!-- We add a <transmission> block for every joint that we wish to actuate. -->

  <xacro:macro name="tilt_joint_transmission" params="number joint_name">
    <transmission name="tilt_joint_transmission_${number}">
      <type>transmission_interface/SimpleTransmission</type>
      <actuator name="tilt_joint_motor_${number}">
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
      <joint name="${joint_name}">
        <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
      </joint>
    </transmission>
  </xacro:macro>

</robot>